{
 "title": "Computer settings",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU/RAM",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"measValue\") FROM \"http_listener_v2\" WHERE (\"streamId\" = '0' AND (\"measObjLdn\" = 'cpu' OR \"measObjLdn\" = 'virtual_memory')) AND $timeFilter GROUP BY time(2s), \"measObjLdn\" fill(null)\n"
    }
   ]
  },
  {
   "title": "CPU frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "SELECT mean(\"measValue\") FROM \"http_listener_v2\" WHERE (\"streamId\" = '0' AND \"measObjLdn\" = 'cpu_frequency') AND $timeFilter GROUP BY time(2s), \"measId\" fill(null)\n"
    }
   ]
  },
  {
   "title": "Core temperatures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "query": "SELECT mean(\"measValue\") FROM \"http_listener_v2\" WHERE (\"streamId\" = '0' AND \"measObjLdn\" = 'temperature') AND $timeFilter GROUP BY time(2s), \"measId\" fill(null)\n"
    }
   ]
  }
 ]
}